### ISSUE TITLE
gh-pages

### ISSUE THREAD

**Issue by linonetwo** [LaoshuBaby/OpenCheckSkirt#2]
直接可以看的网站还是搞一个吧

**Comment by LaoshuBaby** [comment]
这套库目前只有C++写的程序
而且已经不打算继续用的，打算直接重构
因为当时是还在大一大二的时候学写简单的能有GUI界面的小玩具，本着这样的心态写的

如果要直接能在线看的话，可能需要一些node技术栈的程序帮忙

**Comment by LaoshuBaby** [comment]
主要是小警察出警太厉害，做这个没有任何价值，只会被国内JK圈的小警察出警，甚至有人根据留下的邮箱人肉我
不过程序员格子衫方面的数据集我还是想搞一搞的

包括GAN方法和rand方法都想搞一搞

**Comment by LaoshuBaby** [comment]
如果有时间吧，如果有时间的话或许我会试着做一下（但是手头的坑已经很多了，够呛，毕竟国内压力还是很大的，不一定有足够的时间能做喜欢的事情）

**Comment by linonetwo** [comment]
好吧，我理解，在学校会累点，毕业了就爽了，看我的小绿格子哈哈
